## FOLDERS ##
ATTACKS_PLOTS_FOLDER = 'attacks_plots/'
BENIGN_PLOTS_FOLDER = 'benign_plots/'
BY_PROTOCOLS_FOLDER = 'by_protocols/'
BY_ATTACK_CAT_FOLDER = 'by_attack_cat/'
DATA_FOLDER = 'data/'
EXTRACTED_DATASETS = 'extracted_datasets/'
MODEL_PATH = 'models/models_{0}/'
MODEL_ANOMALY_PATH = 'anomaly_{1}/'
MODEL_CATEGORY_PATH = 'category_{1}/'
ORIGINAL_FOLDER = 'original/'
PLOTS_FOLDER = 'plots/'
PREDICTIONS_BENIGN = 'predictions_benign/'
PREDICTIONS_ATTACK = 'predictions_attack/'
PREPROCESSED_CATEGORY_FOLDER = 'preprocessed_category/'
PROCESSED_ANOMALY_FOLDER = 'processed_anomaly/'
SAVINGS_FOLDER = 'savings/'
METRICS_FOLDER = 'metrics/'

## CSV FILENAMES ##
ATTACKS_FILENAME = 'attacks_dataset.csv'
BENIGN_FILENAME = 'benign_dataset.csv'
CONFUSION_MATRIX_FILENAME = 'confusion_matrix'
CONFUSION_TEST_MATRIX_FILENAME = 'confusion_matrix_test'
EXTRACTED_BENIGN_DATA_FILENAME = 'Benign_dataset.csv'
EXTRACTED_ATTACK_DATA_FILENAME = 'All_attacks_dataset.csv'
EXTRACTED_ATTACK_CAT_DATA_FILENAME = '{1}_dataset.csv'
METRICS_CLASSIFICATION_WINDOW_FILENAME = 'metrics_classification_window.txt'
METRICS_CLASSIFICATION_TEST_FILENAME = 'metrics_classification_test.txt'
METRICS_REGRESSION_FILENAME = 'metrics_regression.txt'
PARTIAL_CSVS_FILENAME = 'UNSW-NB15_{0}.csv'
ROC_CURVE_FILENAME = 'roc_curve'
ROC_CURVE_TEST_FILENAME = 'roc_curve_test'
SELECTED_FEATURES_FILENAME = 'selected_features.json'
UNPROCESSED_TRAINING_SET_FILENAME = 'UNSW_NB15_training-set.csv'
UNPROCESSED_TESTING_SET_FILENAME = 'UNSW_NB15_testing-set.csv'
CAT_TEST_DATASET_FILENAME = 'test_dataset.csv'
CAT_TRAIN_DATASET_FILENAME = 'train_dataset.csv'
CAT_TEST_UPSAMPLED_DATASET_FILENAME = 'test_dataset_upsampled.csv'
CAT_TRAIN_UPSAMPLED_DATASET_FILENAME = 'train_dataset_upsampled.csv'
WHOLE_DATASET_FILENAME = 'whole_dataset.csv'


## FOLDER PATHS ##
PROCESSED_BY_ATTACKS_FOLDER   = DATA_FOLDER + PROCESSED_ANOMALY_FOLDER + '{0}/' + BY_ATTACK_CAT_FOLDER
PROCESSED_ATT_PROTOCOL_FOLDER = DATA_FOLDER + PROCESSED_ANOMALY_FOLDER + '{0}/' + BY_ATTACK_CAT_FOLDER + '{1}/{2}/'
ATTACKS_PLOTS_BY_ATT_FOLDER   = DATA_FOLDER + PROCESSED_ANOMALY_FOLDER + '{0}/' + BY_ATTACK_CAT_FOLDER + '{1}/{2}/' + PLOTS_FOLDER

PROCESSED_BY_PROTOCOLS_FOLDER = DATA_FOLDER + PROCESSED_ANOMALY_FOLDER + '{0}/' + BY_PROTOCOLS_FOLDER
PROCESSED_PROTOCOL_FOLDER     = DATA_FOLDER + PROCESSED_ANOMALY_FOLDER + '{0}/' + BY_PROTOCOLS_FOLDER + '{1}/'
ATTACKS_PLOTS_BY_PROT_FOLDER  = DATA_FOLDER + PROCESSED_ANOMALY_FOLDER + '{0}/' + BY_PROTOCOLS_FOLDER + '{1}/' + ATTACKS_PLOTS_FOLDER
BENIGN_PLOTS__BY_PROT_FOLDER  = DATA_FOLDER + PROCESSED_ANOMALY_FOLDER + '{0}/' + BY_PROTOCOLS_FOLDER + '{1}/' + BENIGN_PLOTS_FOLDER


## CSV FILE PATHS - UNPROCESSED RAW ##
UNPROCESSED_PARTIAL_CSV  = DATA_FOLDER + ORIGINAL_FOLDER + PARTIAL_CSVS_FILENAME
UNPROCESSED_TESTING_SET  = DATA_FOLDER + ORIGINAL_FOLDER + UNPROCESSED_TESTING_SET_FILENAME
UNPROCESSED_TRAINING_SET = DATA_FOLDER + ORIGINAL_FOLDER + UNPROCESSED_TRAINING_SET_FILENAME

## CSV FILE PATHS - PROCESSED RAW ##
PREPROCESSED_CAT_FOLDER = DATA_FOLDER + PREPROCESSED_CATEGORY_FOLDER
CAT_TRAIN_DATASET = PREPROCESSED_CAT_FOLDER + CAT_TRAIN_DATASET_FILENAME
CAT_TEST_DATASET = PREPROCESSED_CAT_FOLDER + CAT_TEST_DATASET_FILENAME
CAT_UPSAMPLED_TRAIN_DATASET = PREPROCESSED_CAT_FOLDER + CAT_TRAIN_UPSAMPLED_DATASET_FILENAME
CAT_UPSAMPLED_TEST_DATASET  = PREPROCESSED_CAT_FOLDER + CAT_TEST_UPSAMPLED_DATASET_FILENAME
WHOLE_DATASET = PREPROCESSED_CAT_FOLDER + WHOLE_DATASET_FILENAME

## CSV FILE PATHS - PROCESSED TS PER PROTOCOL ##
TS_ATTACK_DATASET_PATH = PROCESSED_PROTOCOL_FOLDER + ATTACKS_FILENAME
TS_BENIGN_DATASET_PATH = PROCESSED_PROTOCOL_FOLDER + BENIGN_FILENAME
TS_ATTACK_CATEGORY_DATASET_PATH = PROCESSED_ATT_PROTOCOL_FOLDER + ATTACKS_FILENAME

## CSV FILE PATHS - EXTRACTED DATASET PATH ##
EXTRACTED_DATASETS_FOLDER = DATA_FOLDER + PROCESSED_ANOMALY_FOLDER + '{0}/' + EXTRACTED_DATASETS
EXTRACTED_ATTACK_DATASET_PATH = EXTRACTED_DATASETS_FOLDER + EXTRACTED_ATTACK_DATA_FILENAME
EXTRACTED_BENIGN_DATASET_PATH = EXTRACTED_DATASETS_FOLDER + EXTRACTED_BENIGN_DATA_FILENAME
EXTRACTED_ATTACK_CAT_DATASET_PATH = EXTRACTED_DATASETS_FOLDER + EXTRACTED_ATTACK_CAT_DATA_FILENAME


## TRAINED MODEL PATHS ##
SAVE_ANOMALY_MODEL_PATH = MODEL_PATH + SAVINGS_FOLDER + MODEL_ANOMALY_PATH
SAVE_CAT_MODEL_PATH = MODEL_PATH + SAVINGS_FOLDER + MODEL_CATEGORY_PATH


## MODELS METRICS ##
METRICS_FOLDER = MODEL_PATH + METRICS_FOLDER
MODEL_REGRESSION_METRICS_PATH = METRICS_FOLDER + METRICS_REGRESSION_FILENAME
MODEL_CLASSIFICATION_METRICS_WINDOW_PATH = METRICS_FOLDER + METRICS_CLASSIFICATION_WINDOW_FILENAME
MODEL_CLASSIFICATION_METRICS_TEST_PATH = METRICS_FOLDER + METRICS_CLASSIFICATION_TEST_FILENAME

MODEL_CONF_MATRIX_PATH = METRICS_FOLDER + CONFUSION_MATRIX_FILENAME
MODEL_CONF_TEST_MATRIX_PATH = METRICS_FOLDER + CONFUSION_TEST_MATRIX_FILENAME

MODEL_METRICS_ROC_PATH = METRICS_FOLDER + ROC_CURVE_FILENAME
MODEL_METRICS_ROC_TEST_PATH = METRICS_FOLDER + ROC_CURVE_TEST_FILENAME

MODEL_PREDICTIONS_BENIGN_PATH = MODEL_PATH + PREDICTIONS_BENIGN
MODEL_PREDICTIONS_ATTACK_PATH = MODEL_PATH + PREDICTIONS_ATTACK

METRICS_FOLDER


## OTHERS ##
USELESS_FEATURES_FOR_PARTIAL_CSVS = ['srcip', 'sport', 'dstip', 'dsport', 'Stime', 'Ltime', \
                                     'dur', 'state', 'proto', 'Label', 'ct_ftp_cmd'] # ct_ftp_cmd is mainly empty
USELESS_FEATURES_FOR_CATEGORIZE = ['id', 'label', 'rate', 'dur', 'state', 'proto', 'service', 'ct_ftp_cmd']

PROTOCOLS = ['all', 'dns', 'ftp', 'ftp-data', 'http', 'smtp', 'ssh']  # pop3 was removed(no attacks)
ATTACK_CATEGORIES = ['Analysis', 'Backdoor', 'DoS', 'Exploits', 'Fuzzers', 'Generic', 'Reconnaissance', 'Shellcode', 'Worms']

REAL_DATASET = 'data/real/buffer_2021-04-15_2021-05-26.tsv'
REAL_DATASET_FEATURES = ['conn_count_uid_in', 'conn_count_uid_out', 'dns_count_uid_out', 'http_count_uid_in', 'ssl_count_uid_in']

CORELLATIONS_FILE_PATH = DATA_FOLDER + PROCESSED_ANOMALY_FOLDER + '{0}/correlations/'
CORELLATIONS_PNG_FILE = CORELLATIONS_FILE_PATH + '{1}_matrix.png'

SELECTED_FEATURES_JSON = DATA_FOLDER + PROCESSED_ANOMALY_FOLDER + '{0}/' + SELECTED_FEATURES_FILENAME

TIME = 'time'
TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
PRETTY_TIME_FORMAT = '%d.%m %H:%M'